### ISSUE TITLE
KeyValuePair Serialization Error

### ISSUE THREAD

**Issue by QianMoXi** [ExtendedXmlSerializer/home#372]
Just like this:
` var serializer = new ConfigurationContainer() .UseOptimizedNamespaces() .Create();
            var document = serializer.Serialize(new XmlWriterSettings(){Indent = true},
                                                new KeyValuePair<string, object>("123", "123"));`

Key and Value are not included in the results:
`<KeyValuePair xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:arguments="string,Object" xmlns="https://extendedxmlserializer.github.io/system" />`

I think the result should be like this:
`<KeyValuePair xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:arguments="string,Object" xmlns="https://extendedxmlserializer.github.io/system" >
    <Key>123</Key>
    <Value>123</Value>
</KeyValuePair>`

**Comment by Mike-EEE** [comment]
Hey @QianMoXi thanks for writing in.  I thought for sure you found a bug but this is actually intended behavior.  If you look at `KeyValuePair.Key` and `KeyValuePair.Value` they are both get-only and do not have writable setters.

In order to serialize these objects, you will have to make use of the `EnableParameterizedContent` call.  I have demonstrated this in the form of a passing test here:

https://github.com/ExtendedXmlSerializer/home/blob/038076b2afe15514ab7e35bfbe4724c819954102/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue372Tests.cs#L14-L19

Please let me know if this helps you out and/or if you have any further questions or issues with ExtendedXmlSerializer. 👍

**Comment by QianMoXi** [comment]
This is very useful to me.
Sorry, I don't look at the document carefully.

**Comment by Mike-EEE** [comment]
Glad to hear, @QianMoXi!  Thanks for stopping by. 😊
