### ISSUE TITLE
Startup time (creating an `IExtendedXmlSerializer`) is incredibly slow

### ISSUE THREAD

**Issue by LPeter1997** [ExtendedXmlSerializer/home#392]
I've noticed that serializing doesn't take too long, but the configuration, even just for trivial cases takes waaaay too long. Running this:

```csharp
var sw = Stopwatch.StartNew();
IExtendedXmlSerializer serializer = new ConfigurationContainer().Create();
var elapsed = sw.ElapsedMilliseconds;
Console.WriteLine($"{elapsed} ms");
```

Yields around 1.5 seconds, which is very annoying, when my app used to start up in less than a hundredth of this. Why does this take so long?

Does this mean I have to cache my serializer and not even attempt to construct one as I need?

**Comment by Mike-E-wins** [comment]
Yikes!  That does sound bad, @LPeter1997.  Thank you for reporting it.  When we first created v2 performance was a focus but it has not been one for some time now.  We have indeed focused on runtime but not configuration/startup time.

I will poke around and see if there is anything obvious that we can tackle and update here. 👍

**Comment by Mike-E-wins** [comment]
OK I have created a simple test that emits startup times.  Locally I get:

```
net452: 340 ms
net471: 313 ms
netcoreapp2.1: 260 ms
```

This is not outstanding but not a concern either and seems within expected range.

[In our build](https://ci.appveyor.com/project/ExtendedXmlSerializer/extendedxmlserializer/builds/32784293/tests) (search for `ExtendedXmlSerializer.Tests.ReportedIssues.Issue392Tests.Verify`) these also appear to be nominal however I think that at this point the domain has already initialized and any assembly/domain-based initialization issues have already been attended.

Have you attempted to try this in a new console project altogether to see if you get the same results?  It may be due to your referenced assemblies and/or projects, I am thinking.  Please let me know of your findings and I will see if I can help you towards resolving this. 👍

**Comment by LPeter1997** [comment]
I've tried to add the library with NuGet in a new console app, even tried to clone the source and reference directly that. No difference here, still around one and a half seconds just to create a serializer in a .NET Core project.

**Comment by Mike-E-wins** [comment]
Boo.  I am stumped for ideas, then.  Do you have an older computer?  Maybe another computer to try things out on to see how it fares?  I myself am on a Ryzen 2700x system, so not exactly new but not old either, around 4Ghz.  We are basically seeing a 6x difference between environments so this would imply that you have a processor that is 6x slower, so want to verify if possible as a basic sanity check.

The other consideration that comes to mind is the .NET Core runtime installed in your environment.  I am running 3.1 here,  That *shouldn't* make any difference, but again exploring considerations.

I would also be interested in seeing what your results are in .NET Framework if you have any installed.  It should be slower, but again, offering considerations to further diagnose this.

**Comment by Mike-E-wins** [comment]
There hasn't been any activity on this issue for nearly a month now.  Please feel free to comment/reply and we can take it from there.  Closing for now.
