### ISSUE TITLE
how to deserialize this xml?

### ISSUE THREAD

**Issue by deRightDirection** [ExtendedXmlSerializer/home#406]
i have the following xml.

```
<triggerbericht
        version="1.5-20191120"
        xmlns="http://www.omgevingswet.nl/koppelvlak/IMAM"
        xmlns:tb="http://www.omgevingswet.nl/koppelvlak/trigger"
        xmlns:ic="http://www.omgevingswet.nl/koppelvlak/common"
        xmlns:gml="http://www.opengis.net/gml">
    <stuurgegevens>
        <zender>
            <organisatie>DSO</organisatie>
            <applicatie>DSO-LV</applicatie>
        </zender>
        <ontvanger>
            <organisatie>00000000000123456789</organisatie>
        </ontvanger>
     </stuurgegevens>
    <trigger>
        <tb:doel>Initieren</tb:doel>
        <tb:indienDatum>2018-05-01T00:00:00.000</tb:indienDatum>
    </trigger>
</triggerbericht>
```
how do i deserialize it now? I can't find anything in the documentation about how to handle with namespaces.

**Comment by Mike-E-wins** [comment]
Hi @deRightDirection thanks for writing in.  As you've read the documentation, I'm sure you've seen [the section regarding classic serialization vs. POCO-graph serialization](https://github.com/ExtendedXmlSerializer/home/wiki/FAQs#systemxmlserializer-vs-extendedxmlserializer), which is the intended focus of ExtendedXmlSerializer.  

If you are looking to deserialize a POCO that is based on a specialized external schema+document, as you have in your scenario above, I would suggest to first serialize the object in ExtendedXmlSerializer to see what its expected XML should look like, then run your external XML file (the one presented above) through an XSLT file to get it to the expected output so that ExtendedXmlSerializer can read it.

Not ideal and I know it's a bit of a hassle, but again ExtendedXmlSerializer is best used (and intended) for serializing/deserializing POCOs directly rather than processing existing files from external systems.  Please let me know if you have any further questions and I will do my best to assist you.

**Comment by Mike-E-wins** [comment]
There hasn't been any activity here for a few weeks on this issue so will close for now.  Please let me know if you have any further questions and I will do my best to answer them for you. 👍
