### ISSUE TITLE
Range<int>

### ISSUE THREAD

**Issue by WojciechNagorski** [ExtendedXmlSerializer/home#435]
I got email:

> Dear Mr. Nagórski,
> 
> we are trying to serialize using the ExtendedXmlSerializer.
> Unfortunately the latest version we can use is 2.0.0. Its working great
> in general. But we have a problem to serialize Range<int>. Serialization
> is working fine, but not the deserialization.
> 
> We would appreciate it very much, if You had a quick look at the
> problem, maybe you have an idea for a fix or workaround. Thank you very
> much!
> 
> Here is how we build the Serializer:
> 
> IExtendedXmlSerializer XmlSerializer = new ConfigurationContainer()
>                 .ConfigureType<Monatswerte>().EnableReferences(m => m.Id)
>                 .Type<JahrMonat>().CustomSerializer(new
> JahrMonatSerializer())
>                
> .Type<Range<int>>().CustomSerializer(rangeSerializer).Name("RangeInt").Create();
> 
> And here is the custom serializer:
> 
> public class RangeIntSerializer : IExtendedXmlCustomSerializer<Range<int>>
>     {
>         public Range<int> Deserialize(XElement element)
>         {
>             return new Range<int>(
>                 int.Parse(element.Member(nameof(Range<int>.Min)).Value),
>                 int.Parse(element.Member(nameof(Range<int>.Max)).Value));
>         }
> 
>         public void Serializer(XmlWriter writer, Range<int> obj)
>         {
>             writer.WriteElementString("Min", obj.Min.ToString());
>             writer.WriteElementString("Max", obj.Max.ToString());
>         }
>     }
> 
> When we try to deserialize:
> 
> x =  XmlSerializer.Deserialize(reader) as ...
> 
> For the case, that reader is at a "RangeInt", it cannot find the right
> deserializer and returns null. So, it cannot find the custom
> serializer's deserialzer for "RangeInt".
> 
> The execption is:
> 
> "Der Wert darf nicht NULL sein.\r\nParametername: key"  -> "The value
> should not be NULL. \r\nParametername : key"
> 
> 
> Here is what the xml for RangeInt looks:
> 
> ...
> 
>         <RangeInt xmlns="clr-namespace:
> XXXX.YYY.PersDataTypes.Basic;assembly=XXXX.YYY.PersDataTypes.Basic">
>           <Min>0</Min>
>           <Max>9999999</Max>
>         </RangeInt>
> 
> ...
> 
> Kind Regards
> 
> Till Späth

**Comment by Mike-E-angelo** [comment]
Greetings!  Hopefully Till can meet us on here.  I will also reply to the email.

The first issue here is that I understand you are only able to use 2.0.0.  Obviously we are on v3 now and so much has happened since v2.

However, you should be able to serialize the `Range` object by making use of the `EnableParameterizedContent` method.  I have created a passing test in our suite to demonstrate this here:

https://github.com/ExtendedXmlSerializer/home/blob/81da0607e13191e6d9aa7fbc5ad4cb5117c41a8d/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue435Tests.cs#L10-L29

The other complication is that I am not sure which `Range` you are referencing.  I made a place holder struct in the test that contains the properties that are mentioned in the email.

Please let me know if you have any further questions/concerns and I will try my best to assist.  I am not if you are somehow able to use v3, but that would be ideal, too. :)

**Comment by ubik80** [comment]
Thank You very much for your quick help! It solved our problem. 

It works with .EnableParameterizedContent() in combination with EnableImplicitTyping().

... .Type<List<int>>().Name("ListInt").EnableImplicitTyping(typeof(List<int>)).EnableParameterizedContent();   

(List instead of Range, but issue was the same)

**Comment by Mike-E-angelo** [comment]
Woohoo!  Great to hear.  These are the kind of problems I like. :)  Please feel free to ask any additional questions you might have here on GitHub and I can do my best to get you situated.  Even though we are on v3 now there is still a lot of functionality that is shared with v2, so we might be able to help you out.  Open a new issue here and we'll see how we do. 👍  Closing this for now.
