### ISSUE TITLE
Empty tag deserialization

### ISSUE THREAD

**Issue by hostar** [ExtendedXmlSerializer/home#445]
Hello,

I am having following problem with deserialization.

When I try to deserialize empty element like this, it works:
`<LastName></LastName>`

but when the empty element look like this, it does not work:
`<LastName/>`

This is how I create serializer instance:
`var serializer = new ConfigurationContainer().EnableImplicitTyping(typeof(SampleModel)).Create();`

Is there any way how to configure serializer in order to make it work? Or is it a bug?

Here is demo repository with sample data, just run project "RunMe": [Github link](https://github.com/hostar/ExtendedXmlSerializer_issue_demo1)

Thank you for help in advance.

**Comment by Mike-E-angelo** [comment]
Hello @hostar, thank you for writing in with this.  This appears to be an issue with the use of `XmlTextReader`. If I use `XmlReader.Create(stream)` this seems to work as expected.  I have provided a passing test of this for your review here:

https://github.com/ExtendedXmlSerializer/home/blob/ff303d4e991fab007fa245a119975d3abb7c373d/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue445Tests.cs#L13-L114

While we do provide compatibility for classic readers, our APIs really expect and support the use of `XmlReader.Create`, which is the recommended/traditional way of creating a reader based on input (stream).  Since `XmlReader` is an abstract class and there can be any number of implementations, ensuring 100% support for each and every one is unfortunately not a supported scenario.  That stated, if there is a bug somewhere in how we are handling the reading with `XmlTextReader`, I will gladly accept a PR to review and fix it.

Please let me know if you have any further questions/issues/concerns around this and I will do my best to assist you. 👍

**Comment by hostar** [comment]
Thank you very much, that was it. It did not even occur to me that could be a problem.
The specific reason for this behavior is the `XmlTextReader` is returning `CanReadValueChunk` as `false` in case of empty element:

https://github.com/ExtendedXmlSerializer/home/blob/ec86d89cdd2e03c1fd6ee5cbef60e5420c00550e/src/ExtendedXmlSerializer/ExtensionModel/Xml/XmlReader.cs#L50

Even though I would be probably able to fix it somehow, as I look how advanced your code is, my fix really would not be in accordance with the rest of project.

Therefore I consider this solved.

**Comment by Mike-E-angelo** [comment]
Oh wow weird.  Yeah, it is saying in the comments of `XmlTextReader.CanReadValueChunk` that it is unsupported.  Probably not a robust solution, but you could override `XmlTextReader` and force it to be `true`.  I provided an example test of this for you here:

https://github.com/ExtendedXmlSerializer/home/blob/23186442fdc12245384779648cf1da6825b7f17b/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue445Tests.cs#L51-L94

In any case, glad we got you pointed in a good direction. 👍
