### ISSUE TITLE
How are exs:identity numbers assigned?

### ISSUE THREAD

**Issue by gmkado** [ExtendedXmlSerializer/home#454]
I am running into an issue when I enable references in my configuration.  

In my application I determine whether a data object requires saving to file by comparing it's md5 hash to a previously saved hash value stored separately.  For some reason my unchanged objects that had references were always requiring a resave.

I tracked it down to the exs:identity and exs:reference numbers being incremented with every serialization.  I'm guessing this is because there is some internal cache of the references and my "SaveAndRestore" function is causing Ref1/Ref2 to no longer be the same object. 

I only care that the references within a given object are maintained.  Is there a way to reset this internal cache so my exs:identity and exs:reference numbers always start at the same index for a given serialization?

        public class Foo
        {
            public Foo Ref1 {get; set;}
            public Foo Ref2 { get; set;}
        }

        [Test]
        public void PlaygroundReferenceTest()
        {
            var serializer = new ConfigurationContainer()
                .UseAutoFormatting()
                .UseOptimizedNamespaces()
                .EnableReferences()
                .Create();

            var myRef = new Foo();
            Foo myObj = new Foo
            {
                Ref1 = myRef,
                Ref2 = myRef
            };

            var hashes = new List<string>();  // <--- THESE SHOULD ALL BE THE SAME AFTER THE FOR LOOP
            for (int i = 0; i < 10; i++)
            {
                myObj = SaveAndRestore(myObj);
                hashes.Add(GetHash(myObj));
            }

            // THIS IS HOW I CHECK IF THE OBJECT REQUIRES BEING SAVED TO DISK
            string GetHash(Foo obj)
            {
                var str = Serialize(obj);
                using (var md5 = MD5.Create())
                using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(str)))
                {
                    return Convert.ToBase64String(md5.ComputeHash(stream));
                }
            } 

            // THIS SIMULATES A SAVE TO DISK AND THEN RESTORE FROM DISK
            Foo SaveAndRestore(Foo obj)
            {
                return Deserialize(Serialize(obj));
            }

            string Serialize(object obj)
            {
                return serializer.Serialize(
                    new XmlWriterSettings { Indent = true }, obj);
            }

            Foo Deserialize(string str)
            {
                return serializer.Deserialize<Foo>(str);
            }
        }

Result:
![image](https://user-images.githubusercontent.com/6592135/94392183-5dcec780-010c-11eb-986a-ab23788f26c3.png)

A comparison of the serialization shows the root cause:
![image](https://user-images.githubusercontent.com/6592135/94392310-bdc56e00-010c-11eb-867b-064a746aee47.png)

**Comment by Mike-E-angelo** [comment]
Good find, @gmkado!  I am thinking that when I originally made this I was attempting to impact performance so that the generated id for each object in memory would only be calculated once per container/domain.  As you denote, however, that results in unexpected IDs for subsequent serializations.  I am in agreement that subsequent serializations of the same entity graph should produce the same XML each and every time (assuming all values/references are the same).

I have produced a build for you here that addresses this here:
https://github.com/ExtendedXmlSerializer/home/pull/455#issuecomment-699885183

That's the good news.  The "bad" news is that while I could get this deployed to nuget tomorrow, I will be out of town for the following two weeks, and am hesitant to deploy to production and then ghost immediately. 😅  

The concern here of course is that while all tests pass and everything "seems" to be OK with the new scope, someone might be using that as a "feature" (ahhh software!).  I would rather be around to address this appropriately if that is the case.

So, if you're able to work with the above in the meantime and that works for you, then that works for me. 👍

**Comment by gmkado** [comment]
Works for me, thanks!

**Comment by Mike-E-angelo** [comment]
Alrighty, this is now deployed and published in NuGet for you:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let me know if you having any further problems and I will investigate.  Closing for now.
