### ISSUE TITLE
`WithUnknownContent` Does Not Support List Members

### ISSUE THREAD

**Issue by netaques** [ExtendedXmlSerializer/home#473]
Hello and thank you very much for the EXS library. I would like to ask about the way how unknown elements are deserialized into array/list items. Please consider following example. Currently extended serializer creates an instance of animal per each inner element of `Animals` node even for cases that element name is not `Animal`. Is there a way to configure EXS not do so and skip these unknown elements? This behavior differs from standard `XmlSerializer` which does not deserialize unknown child elements. Any help would be very appreciated.

```c#
[Test]
public void ShouldIgnoreUnknownXmlArrayItems()
{
    var input = "<Zoo><Animals><Animal/><Animal/><Human/></Animals></Zoo>";

    var serializer = new ConfigurationContainer()
        .Type<Zoo>()
        .Name("Zoo")
        .EnableImplicitTyping(typeof(Zoo))
        .Create();

    var contentStream = new MemoryStream(Encoding.UTF8.GetBytes(input));
    var reader = XmlReader.Create(contentStream));
    var deserialized = (Zoo) serializer.Deserialize(reader);

    Assert.That(deserialized.Animals.Count, Is.EqualTo(2));
}

public class Zoo
{
    public List<Animal> Animals { get; set; }
}

public class Animal
{
}
```

I was trying to play around with `WithUnknownContent` method and put breakpoint into `Call` lambda as described in #256 . However the breakpoint was never hit by debugger. 

```c#
.EnableReaderContext()
.WithUnknownContent().Call(reader =>
{
    // debugger never reach this code
    var content = reader.Content();
})
```

**Comment by Mike-E-angelo** [comment]
Hey @netaques thanks for writing in and for the kind words.  I did take a look at your sample code, and it looks like you found the method that deals with this area, `WithUnknownContent`.

Unfortunately, it looks like there are a few issues here with your scenario.  It seems that if unknown content is encountered in a list element context, it does continue but it still creates an element of the current list being constructed.  So in my test, I created two animals, one human, and then one animal, and it constructed 4 animals when `WithUnknownContent().Continue()` applied.  This, of course, is not expected and should not happen.

Also, as you've noted, it appears there's an entire bug altogether with the `Call` method not firing.  So that makes two issues right out of the gate with this configuration call.

It would seem `WithUnknownContent` is best utilized with content serving as properties and not for list elements.

The reader is somewhat of a sore spot in the code, and this is a good example.  I can poke around here to see if there's something obvious going on, but I am not too optimistic about this due to the fragility of the code in this area of the library.  

EXS's bread and butter is deserializing documents that it has written.  That, of course, means no unknown elements.  If you are needing to process unknown content in your document that wasn't written by EXS, my recommendation would be to use XSLT to first process the document to remove unknown elements, and then send that over to EXS for further processing.  Just preparing you here for the worst-case scenario towards resolving this issue. 😁

In the meantime, I will further look into this for you and let you know of any findings. 👍

**Comment by Mike-E-angelo** [comment]
Alright, @netaques I've taken a look into this, and it's not pretty.  I was correct in my earlier assumption that `WithUnknownContent` is only supported by properties, and not list elements.  

We're facing some challenges here, in that the list element reader/activator doesn't actually read the element names to create the type.  It will only read the element for an `exs:type` tag to instantiate a type that is different from the target list type element.  So, for example, in the case of a `List<Animal>` a new instance of `Animal` is created unless there is an `exs:type` attribute in which case that type will be instantiated instead.

Incidentally, this is a big part of the reason why we do not support the `XmlElement`/inner/default content that the classic serializer allows (more of this in #240).

I am going to muse about this some more, but it doesn't look promising at the moment.  This might be something that gets left to the community to address at some point, if someone is daring enough with a PR.

**Comment by Mike-E-angelo** [comment]
FWIW marking this issue as `helpwanted/won't fix` as it unfortunately falls outside of the allotted/due-diligence time I have per #383.  I will leave it open for the community to take a look at for a while and then archive it if no one takes up the challenge.

**Comment by netaques** [comment]
Hi @Mike-E-angelo, I took a look on this issue and tried to identify how it might be fixed. To be honest the reader code is not as clean as it could be, so that I am not pretty sure if my findings are on the right track or if it is totally out. I think I got the point where I know what and where should be done, but I would like to ask you how. I think that problem is in method `CollectionInnerContentHandler.IsSatisfiedBy`:
```c#
public bool IsSatisfiedBy(IInnerContent parameter)
{
	var result = _specification.IsSatisfiedBy(parameter);
	if (result)
	{
		_handler.Handle((IListInnerContent)parameter, _item);
	}

	return result;
}
```
Call of `_specification.IsSatisfiedBy` points to `ListContentsSpecification` that checks:
- If parameter is XmlElement by `ElementSpecification`,
- And if it is of type `IListInnerContent` by `IsTypeSpecification<IListInnerContent>` .

Would it be possible to somehow check if generic type of list that is stored in `parameter.Current` is compatible with the reader returned by `parameter.Get()`? If this is possible, it might be a solution to write another specification that would check it and include it in  `ListContentsSpecification` along with current two specifications.

**Comment by Mike-E-angelo** [comment]
> To be honest the reader code is not as clean as it could be

That's putting it nicely. 😅  To be more succinct, the code is downright _terrible_. 😂😭  When I originally wrote that code, I was going through a phase, shall we say, of being a little too obsessed with performance.  I was learning quite a lot, but was still confused on a lot of things.  The result of which was that I was designing things unnecessarily terribly and putting performance before design.  I've learned from that, but unfortunately the design of the reader still suffers and reflects as such.  What makes matters worse is that the reader was so bad that it didn't work, and I got into a "get it working now" frenzy to get it to where it would work and we could push out v2.

I fret with embarrassment whenever I dig through that code.

ANYWHOO, I am SUPER appreciative of you taking the time to dig through that embarrassment, and posing your question ... because you were spot on!  I was able to add another check there if you enable the `WithUnknownContent` extension and provide some unknown content.

Check out this build and see how it treats you now:

https://github.com/ExtendedXmlSerializer/home/pull/487#issuecomment-737834686

**Comment by netaques** [comment]
Thank you Mike. I am glad to see that I was almost there. Yesterday I was just playing with that `UnknownContentHandlingExtension.Services` class but I did not know about the `IClassification` that does the magic. And regarding the design of code - to be honest, show me a good developer who never wanted to delete whole solution and start all over.

**Comment by Mike-E-angelo** [comment]
This has been deployed to NuGet and deployed here:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Thanks again for your patience and collaboration with this issue.  It is very much appreciated!  I am glad we were able to track this down and it wouldn't have been possible without your sleuthing.  

If you find any additional issues with this please do let me know and I will see if they can be addressed.  Closing for now.
