### ISSUE TITLE
How to drop "exs:type" when serializing derived types

### ISSUE THREAD

**Issue by michalsznajder** [ExtendedXmlSerializer/home#474]
This is not an issue but rather question for help.

I have following object structure:

    class Container
    {
        public string Common { get; set; } = "Common";
        public IBody Body { get; set; }
    }

    interface IBody
    {
        string BodyType { get; set; }
    }

    class A : IBody
    {
        public string BodyType { get; set; } = "A";
        public string FieldX { get; set; } = "FieldX";
    }

    class B : IBody
    {
        public string BodyType { get; set; } = "B";
        public string FieldY { get; set; } = "FieldY";
    }

I serialize it with following code:

```
var serializer = new ConfigurationContainer()
	.UseOptimizedNamespaces()
	.EnableImplicitTyping(typeof(Container))
	.EnableImplicitTyping(typeof(A))
	.EnableImplicitTyping(typeof(B))
	.EnableImplicitTyping(typeof(IBody))
	.Create();
var result = serializer.Serialize(new XmlWriterSettings { OmitXmlDeclaration = true}, container);
```

And I get this as result

   `<Container xmlns:exs="https://extendedxmlserializer.github.io/v2" xmlns="clr-namespace:Namespace.Test;assembly=Test"><Common>Common</Common><Body exs:type="A"><BodyType>A</BodyType><FieldX>FieldX</FieldX></Body></Container>`

Is there any way to get rid of  `exs:type` and rest of namespace related attributes somehow? I am only interested in serialization. 

My receiving party is a custom XML parser and it has problems with namespace parsing...

**Comment by Mike-E-angelo** [comment]
Hi @michalsznajder thank you for writing in and for the question.  Unfortunately, this is not possible.  Interestingly enough, I got involved with ExtendedXmlSerializer when I learned that the classic `System.Xml.Serlialization.XmlSerializer` does not handle/serialize interfaces.  Since this is considered a breaking/unsupported scenario for the classic serializer, we went the route of utilizing a custom namespaced attribute (`exs:type`) to denote the implementing type whenever an interface-based property/element is encountered in the object graph.

All is not lost, however.  In your case, I would use an XSLT transform to transform the resulting serialized ExtendedXmlSerializer document into a document that conforms to the destination's expected schema.  Once that transformed document has been created, you can then pass it to the receiving party, where they should be able to process it since it now conforms to their expectations.

This is the strategy/pattern that I recommend whenever someone needs to use a document (or is receiving one) from an external party that is not using ExtendedXmlSerializer and the format does not meet precise expectations.  XSLT was made specifically for these types of scenarios and is always handy to keep in mind whenever something like this is encountered.

I hope this helps you out.  Please do let me know if that works for you and/or if you have any additional questions around this and I will do my best to assist you. 👍

**Comment by michalsznajder** [comment]
O thanks. It would be nice to have it but I understand. Anyway - great project.

As for my case I resorted for second best thing after XSLT - regex 😃  I will leave it for reference here for future :
```
var cleanupRegex = new Regex("( xmlns:exs=\"[^\"]+\"| xmlns=\"[^\"]+\"| exs:type=\"[^\"]+\")");
var result = _serializer.Serialize(_writerSettings, classWithInterfaces);
result = cleanupRegex.Replace(result, "");
```

BTW would you accept PR that adds option to disable namespace generation?

**Comment by Mike-E-angelo** [comment]
hah!  Good ol' `RegEx`.  Yes, I can understand having to go that route as using Xslt seems like you have to relearn it each time.  The same thing with RegEx but you encounter it more often than Xslt so less relearning involved, so to speak. 😁

As for a PR, sure... if the extension can read back in the same document without throwing an exception and producing the equivalent object graph that was serialized, then it is worth exploring. :)  My primary question, to start, is how you would manage to resolve a type without the namespace?  There needs to be an identifier of some sort so that a differentiating type can be activated.

**Comment by michalsznajder** [comment]
My particular case needs only creation so I am not interested in reading data back. So second issue is not a problem in my case 😄 .

During XML creation I think there should be a way to turn off namespaces. Or rather provide extension point to specify you own typing way.

As for deserialization of XML. Maybe some way to leave part of document as unparsed so library user could decide on type and later run parser on the reminder? Some kind of RawXmlAttribute...

**Comment by Mike-E-angelo** [comment]
Hehe yeah, I am not sure how common this scenario will be, but I certainly appreciate the appeal.  It seems odd to create a feature that only works one way but then essentially breaks it on the other.  Something that has been suggested in the past was to create a new library, something like `ExtendedXmlSerializer.Extensions` that is a culmination/collaboration/compilation of community-produced extensions.  This seems like a candidate for such a compilation.  If you can produce an extension that does something like the above that you are happy with, then I can make it the first contribution of such a library. :)

**Comment by Mike-E-angelo** [comment]
Looks like this issue is as resolved as much as possible at the moment.  If you do find the motivation/courage to create a contribution, please submit a PR and we can take it from there.  In any case, thank you for your interest and considerations with ExtendedXmlSerializer. 👍  Closing for now.
