### ISSUE TITLE
Deserialize attributes

### ISSUE THREAD

**Issue by martinscholz83** [ExtendedXmlSerializer/home#499]
This is more a question than an issue. I have the following xml
```xml
<Settings>
      <v name="szRedirectUrl">https://x.x.x.x</v>      
      <v name="dwFlags">0</v>
      <v name="dwFromTemplateId">2752519</v>
      <v name="dwFromTemplateClassId">450</v>
      <v name="dwIdAssignTemplateId">196610</v>
      <v name="MyLoginClass">      
        <ServerLogin>
            <v name="szServer">blahblah</v>
            <v name="szUser">someUser</v>
            <v name="bUseDomain">0</v>
        </ServerLogin>
      </v>
  </Settings>
```
Is it possible with ExtendedXMLSerializer to deserialize this into some class?

**Comment by Mike-E-angelo** [comment]
Hey there @martinscholz83 thanks for writing in with this.  Unfortunately, ExtendedXmlSerializer will not be able to process this as-is.  My suggestion would be to utilize an XSLT stylesheet to run the above external document through it so that it is in a format that ExtendedXmlSerializer expects and understands.  First, however, you would need to serialize your .NET object via ExtendedXmlSerializer to get a reference document to build your XSLT around.

So it would be a process of:

- Serialize .NET object via ExtendedXmlSerializer to get a target/reference document
- Create XSLT stylesheet based on the reference document
- Acquire External Document (above)
- Apply XSLT to External Document, resulting in a resulting document that ExtendedXmlSerializer expects
- Send the resulting document to ExtendedXmlSerializer to deserialize as .NET object

Please let me know if that makes sense and/or if you have any additional questions around this.  I will do my best to assist in getting you situated. 👍

**Comment by martinscholz83** [comment]
I already had in mind to transform the file or to create my own parser for it. But i got it running with the standard .NET XmlSerializer. It's a little bit messy, but it works for now.

```C#
[XmlRoot("Settings")]
	public class Settings
	{
		[XmlElement("v")]
		public List<V> Vs { get; set; }

		public string m_szIdpUrl {
			get
			{
				var val = Vs.Where(i => i.Name == "szIdpUrl")?.FirstOrDefault()?.Value;
				return val != null ? val : "";
			}
		}

		public string m_szRedirectUrl {
			get
			{
				var val = Vs.Where(i => i.Name == "szRedirectUrl")?.FirstOrDefault()?.Value;
				return val != null ? val : "";
			}
		}

                public ServerLogin m_oSrvLogin {
			get
			{
				var val = Vs.Where(i => i.Name == "oSrvLogin")?.FirstOrDefault()?.ServerLogin;

				var srv = new ServerLogin() { Server = val.Vs.Where(i => i.Name == "szServer")?.FirstOrDefault()?.Value, User = val.Vs.Where(i => i.Name == "szUser")?.FirstOrDefault()?.Value };
				return srv;
			}
		}
...
...
}

public class V
	{
		public V()
        {
			Value = "";
			Name = "";
        }

		[XmlAttribute("name")]
		public string Name { get; set; }

		[XmlText]
		[DefaultValue("")]
		public string Value { get; set; }

		[XmlElement("CDomainServerLogin")]
		public ServerLogin ServerLogin { get; set; }
	}


public class ServerLogin
    {
        [XmlElement("v")]
        public List<V> Vs { get; set; }

       
        public string Server { get; set; }
        public string User { get; set; }
        public bool UseDomain { get; set; }
        public string Pwd { get;set; }

        public ServerLogin()
        {
            Server = "";
            User = "";           
            Pwd = "";
        }
}
```

**Comment by Mike-E-angelo** [comment]
Sounds like this issue/question was resolved for you.  If you have any other further questions please do feel free to open a new issue and I will look into it for you.  Closing for now.
