### ISSUE TITLE
Issue deserializing partially mapped XML

### ISSUE THREAD

**Issue by EverPresent** [ExtendedXmlSerializer/home#500]
I've got several POCO classes that have been deserializing using the standard System.Xml deserializer.  The class map some, but not all of the available properties in the XML.  We're switching to this library for a variety of reasons, but I'm having a slight problem.  I've been able to reproduce the issue using the code/types available in the unit tests.  Is this a bug, or am I just missing some configuration option that needs to be enabled?

Here is my unit tests to reproduce the issue.  Notice, the only thing I changed from other unit tests, was to add `<a><b>test</b></a>` in the middle of the xml payload.  I would expect that the deserializer should silently ignore the XML.  But I end up getting an empty object returned (not even an exception for bad XML or anything).

Thoughts?

```
using ExtendedXmlSerializer.Configuration;
using ExtendedXmlSerializer.Tests.ReportedIssues.Shared;
using ExtendedXmlSerializer.Tests.ReportedIssues.Support;
using FluentAssertions;
using Xunit;

namespace ExtendedXmlSerializer.Tests.ReportedIssues
{
    public class MyNewIssue
	{
		[Fact]
		void ExtraDataCausingProblem()
		{
			const string xml = @"<?xml version=""1.0""?>
						<FooBar xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns=""http://namespace/file.xsd"">
							<a><b>test</b></a>
							<num>12345</num>
						</FooBar>";

			new ConfigurationContainer().InspectingType<Foo>()
			                            .ForTesting()
			                            .Deserialize<Foo>(xml).Number.Should()
			                            .Be(12345);
		}
    }
}
```

**Comment by Mike-E-angelo** [comment]
Thanks for writing in with this, @EverPresent.  I will have to know the schema of `Foo` to help you further, but we do have some handling of unknown content via the `WithUnkownContent` method.

So, something like this for your scenario should get you unblocked:

```
new ConfigurationContainer().InspectingType<Foo>().WithUnknownContent().Continue()
```

Unfortunately, the serializer does indeed stop working when it hits unknown content.  That's been around since v2 and we should have caught it in v3.  If we ever do a v4 we will make sure the default is to throw an exception.  Changing this behavior obviously is breaking so it is something that should happen during a major version change.  That stated, I am not sure if we will ever do get into a v4 with this project, as it is pretty much in maintenance mode now and for the foreseeable future.  Who knows, though. :)

Please do let me know of any further questions you have around your scenario and I will do my best to assist you.

**Comment by Mike-E-angelo** [comment]
Looks like this question was answered as there has not been activity for a while here.  Please do let me know if you have any further questions by replying to this issue and I will do my best to assist.  Closing for now.
