### ISSUE TITLE
Many fat dependencies

### ISSUE THREAD

**Issue by SwissMaWi** [ExtendedXmlSerializer/home#527]
This is the 2nd alternative to .Net XmLSerializer I am trying out.
All I need is get my POCO serialized to simple plain XML without Namespace and other overhead.
I am shocked by the many dependencies on fancy libraries this component has. 
It gives me DLL versioning errors...
Cannot be true that something so simple as XML Serialization needs these dependencies.
So I cannot use it.
My suggestion is that you remove the dependencies.

**Comment by Mike-E-angelo** [comment]
Sorry to hear of your troubles here @SwissMaWi.  Are you using Visual Studio 2019?  The last time I have had any sort of dependency problems was when I was using .NET Framework.  Since using .NETCore2.x+ along with the new NuGet packaging system this has really been a thing of the past for me.  If you can provide more detail on what you're experiencing I may be able to assist, but if you are in .NET Framework that's a little of my scope these days.

**Comment by Mike-E-angelo** [comment]
Going through the issues here.  Please do let me know if you have further questions/issues and I can take a look into it/them for you.  Closing this issue for now.
