### ISSUE TITLE
The prefix 'exs' cannot be expanded into a namespace URI by using the statically known namespaces

### ISSUE THREAD

**Issue by iklougbo** [ExtendedXmlSerializer/home#574]
Could anyone help with this exception? What does it mean.
I am trying to select nodes using xpath with your library and I get this error.

Thanks in advance

**Comment by Mike-E-angelo** [comment]
Hi @iklougbo thank you for writing in.  Unfortunately, I am not sure ExtendedXmlSerializer is a good fit for your scenario here.  Note that while some legacy scenarios work with ExtendedXmlSerializer, its focus is more on serializing and deserializing complex object graphs via XML.  More information around this can be found here:
https://github.com/ExtendedXmlSerializer/home/wiki/FAQs#systemxmlserializer-vs-extendedxmlserializer

That stated you are the first known occurrence of using ExtendedXmlSerializer and XPath. :)  If you are using XPath operations my recommendation is to use the classic serializer for this.  If you have any further questions, however, I can do my best to assist you.

**Comment by iklougbo** [comment]
Hello,
Thanks for your quick reaction. My object graph is also complex. I therefore had to use allow references.
However I also need to validate some xpath logics on it. Do you at least know what my exception message means?

**Comment by Mike-E-angelo** [comment]
I am actually quite surprised you are able to use ExtendedXmlSerializer in this scenario at all, as it's really at the end of the day a wrapper around a `System.Xml.XmlWriter` and `System.Xml.XmlReader`.  XPath operations are done on an XmlDocument/XDocument if I am not mistaken.  It's been a very long time since I have had my nose in such subjects as you can hopefully tell. :)

Unfortunately, without seeing the code and context of how it is used, I am not able to know for certain the error's meaning.  It appears to be complaining about a namespace mapping and actually reads like a native `System.Xml` error.  If you are able to paste the stack trace and/or additional code in how it's breaking I can further assist.

**Comment by iklougbo** [comment]
Here is the trace. Note there is not default namespace in my xml

Wmhelp.XPath2.XPath2Exception: The prefix 'exs' cannot be expanded into a namespace URI by using the statically known namespaces
   at Wmhelp.XPath2.QNameParser.Parse(String name, IXmlNamespaceResolver resolver, String defaultNamespace, XmlNameTable nameTable)
   at Wmhelp.XPath2.YYParser.yyparse(yyInput yyLex)
   at Wmhelp.XPath2.YYParser.yyparse(yyInput yyLex, Object yyd)
   at Wmhelp.XPath2.YYParser.yyparseSafe(Tokenizer tok, Object yyDebug)
   at Wmhelp.XPath2.YYParser.yyparseSafe(Tokenizer tok)
   at Wmhelp.XPath2.XPath2Expression.Compile(String xpath, IXmlNamespaceResolver resolver)
   at Wmhelp.XPath2.XPathNavigatorExtensions.XPath2Select(XPathNavigator nav, String xpath, IXmlNamespaceResolver resolver)
   at Wmhelp.XPath2.XmlNodeExtensions.XPath2SelectNodes(XmlNode node, String xpath, IXmlNamespaceResolver nsmgr)
   at Wmhelp.XPath2.XmlNodeExtensions.XPath2SelectNodes(XmlNode node, String xpath)

**Comment by Mike-E-angelo** [comment]
OK so the problem here is not in ExtendedXmlSerializer but in the documents that it is creating and/or how the `Wmhelp.XPath2.XPath2Expression` is configured.

Are you able to verify that `xmlns:exs="https://extendedxmlserializer.github.io/v2"` is in the document that is being parsed?  If so (and it should be), you might have to configure the `IXmlNamespaceResolver` that is being passed into `XPath2SelectNodes` there to make sure that it is available.

**Comment by iklougbo** [comment]
Yeah I realized the problem is the Xpath 2.0 nuget package instead.
Yes the namespace exs is in the document.
Let me have a look at the how to go about that resolver.

Thanks for your time

**Comment by Mike-E-angelo** [comment]
I am going through older issues here and see that this was answered.  If you do have any further questions please feel free to reply to this thread or open a new one and I will look into it for you.  Closing for now.
