### ISSUE TITLE
How can I deserialize to a private field?

### ISSUE THREAD

**Issue by push-22** [ExtendedXmlSerializer/home#630]
I have this xml:
```
    <Terminate>
        <All/> <!-- may or may not be included, I want to check if it has been though -->
    </Terminate>
```
and would like to deserialize it to a class like this:
```
public class Terminate {
    [XmlElement(ElementName = "All")]
    private bool? _all { get; set; } = null;
    public bool All {
        get { return _all != null; }
    }
}
```
Is this possible?

**Comment by Mike-E-angelo** [comment]
Hey there @push-22 thank you for writing in with this.  I had to do about take here on your `_all` field as it's actually a property.  Oddly enough this does not work with our default pipeline but could probably be modified to work via extension.

If you convert that property into a field it works as expected:

```
	public sealed class Issue630Tests
	{
		[Fact]
		public void Verify()
		{
			var container = new ConfigurationContainer().Create().ForTesting();
			var instance = new Terminate(true);
			container.Cycle(instance).All.Should().BeTrue();

		}

		public class Terminate {
			public Terminate() : this(null) {}

			public Terminate(bool? all) => _all = all;

			[XmlElement(ElementName = "All")]
			private bool? _all = null;
			public bool All {
				get { return _all != null; }
			}
		}

	}
```

Are you able to use a field?  That would be the easiest solution here.  Otherwise, you may have to look into writing an extension for this and that would be some work.

**Comment by push-22** [comment]
Great - that works - Thanks.
